name: Build Storefront
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'apps/storefront/**'
jobs:
  checks:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.1.0
      - name: Use node 22 and pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Build packages
        run: pnpm build
      - name: Build storefront
        run: pnpm build:storefront
      - name: Types
        run: pnpm types:storefront

